version: "3.3"
services:
  mosquitto:
    image: eclipse-mosquitto
    configs:
      - source: mqtt
        target: mqtt2influx-configuration.yaml
    container_name: mosquitto
    ports:
      - 1883:1883
    networks:
      - mqtt2influxdb-network
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./users.conf:/mosquitto/config/users.conf"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    restart: unless-stopped

  mqtt2influxdb:
    container_name: mqtt2influx
    image: emowejago/mqtt2influxdb
    configs:
      - source: mqtt2influxdb
        target: mqtt2influx-configuration.yaml
    ports:
      - "8181:8080"
    networks:
      - mqtt2influxdb-network
    depends_on:
      - influxdb
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - MQTT_BROKER_IP=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=tele/tasmota_FA2296/SENSOR
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - "./influxdb:/var/lib/influxdb2"
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=wejago
      - DOCKER_INFLUXDB_INIT_BUCKET=hichi
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    env_file:
      - .env
    networks:
      -   mqtt2influxdb-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
      - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=wejago
      - DOCKER_INFLUXDB_INIT_BUCKET=hichi
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - INFLUX_REMOTE_URL=${INFLUX_REMOTE_URL}
    env_file:
      - .env
    networks:
      - mqtt2influxdb-network
    restart: unless-stopped
configs:
  mqtt:
    external: true
  mqtt2influxdb:
    external: true

networks:
  mqtt2influxdb-network:
