version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
    networks:
      - mqtt2influx-network
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./users.conf:/mosquitto/config/users.conf"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
      - "./mqtt2influx-configuration.yaml:/mqtt2influx-configuration.yaml"
    restart: unless-stopped

  mqtt2influx:
    container_name: mqtt2influx
    image: wejago/mqtt2influx
    ports:
      - "8181:8080"
    networks:
      - mqtt2influx-network
    depends_on:
      - kafka
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - MQTT_BROKER_IP=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    env_file:
      - .env
    volumes:
      - "./mqtt2influx-configuration.yaml:/mqtt2influx-configuration.yaml"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - mqtt2kafka-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "mqtt"
    networks:
      - mqtt2kafka-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
      - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=wejago
      - DOCKER_INFLUXDB_INIT_BUCKET=hichi
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - INFLUX_REMOTE_URL=${INFLUX_REMOTE_URL}
    env_file:
      - .env
    networks:
      - mqtt2influx-network
    restart: unless-stopped

networks:
  mqtt2influx-network:
