{
 "title": "power consumption",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_name",
    "query": "hichi, tele (Other consumption monitor)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumption for the past 24 hours",
   "type": "timeseries",
   "description": "consumption for the past 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensor\" and\r\n    r._field == \"Current Consumption\" and\r\n    r.device_name == \"${device_name}\"\r\n  )"
    }
   ]
  },
  {
   "title": "Average consumption for the past day",
   "type": "barchart",
   "description": "consumption per hour for the past 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\n\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nts2 = date.sub(from: today(), d: 1d)\r\nte2 = date.sub(from: ts2, d: -24h)\r\n\r\nfrom(bucket: \"mqtt\")\r\n  |> range(start: ts2, stop: te2)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Total Consumption\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> aggregateWindow(every: 1h, fn: spread, timeSrc:\"_start\")"
    }
   ]
  },
  {
   "title": "Average consumption for the last 24 hours",
   "type": "barchart",
   "description": "consumption per hour for the past 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Total Consumption\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> aggregateWindow(every: 1h, fn: spread, timeSrc:\"_start\")"
    }
   ]
  },
  {
   "title": "Average Hourly Consumption - past 12 months",
   "type": "barchart",
   "description": "mid consumption per hour for a day based on the past 12 months",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"mqtt\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) =>\r\n    r.device_name == \"${device_name}\" and\r\n    r._measurement == \"sensor\" and\r\n    r._field == \"Total Consumption\"\r\n  )\r\n|> aggregateWindow(every: 1h, fn: spread, timeSrc:\"_start\")\r\n|> map(fn: (r) => ({r with hour: date.hour(t: r._time)}))\r\n|> group(columns:[\"hour\"], mode: \"by\")\r\n|> mean(column: \"_value\")\r\n|> group()"
    }
   ]
  },
  {
   "title": "Daily consumption - past 7 days ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nts = date.sub(from: today(), d: 1w)\r\nte = today()\r\nfrom(bucket: \"mqtt\")\r\n|> range(start: ts, stop: te)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"Total Consumption\")\r\n|> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n|> aggregateWindow(every: 1d, fn: spread, timeSrc:\"_start\")"
    }
   ]
  },
  {
   "title": "Weekday consumption - past 12 months",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket:\"mqtt\")\r\n|> range(start: -1y)\r\n|> filter(fn: (r) =>\r\nr._measurement == \"sensor\" and\r\nr._field == \"Total Consumption\" and\r\nr.device_name == \"${device_name}\"\r\n)\r\n|> aggregateWindow(every: 1d, fn: spread, timeSrc:\"_start\")\r\n|> map(fn: (r) => ({r with _day: date.weekDay(t: r._time)}))\r\n|> group(columns:[\"_day\"], mode: \"by\")\r\n|> mean(column: \"_value\")\r\n|> group()"
    }
   ]
  },
  {
   "title": "Weekly consumption",
   "type": "barchart",
   "description": "consumption per week for the past 12 months",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nfrom(bucket: \"mqtt\")\r\n  |> range(start: -12mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\" and r[\"_field\"] == \"Total Consumption\" and r[\"sensor_id\"] == \"090145425a01000c82dc\")\r\n  |> aggregateWindow(every: 1w, fn: spread, timeSrc:\"_start\", offset: -3d)\r\n  |> map(fn: (r) => ({r with _week: date.week(t: r._time)}))\r\n  |> group(columns:[\"_week\"], mode: \"by\")\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Monthly consumption",
   "type": "barchart",
   "description": "consumption per month for the past 12 months",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nfrom(bucket: \"mqtt\")\r\n  |> range(start: - 12mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Total Consumption\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\r\n  |> aggregateWindow(every: 1mo, fn: spread, timeSrc:\"_start\")"
    }
   ]
  }
 ]
}