{
 "title": "power consumption",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Consumption for the past 24 hours",
   "type": "timeseries",
   "description": "consumption for the past 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"hichi\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensor\" and\r\n    r._field == \"currentConsumption(16_7_0)\"\r\n  )"
    }
   ]
  },
  {
   "title": "Average consumption for the past day",
   "type": "barchart",
   "description": "consumption per hour for the past 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\n\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nts2 = date.sub(from: today(), d: 1d)\r\nte2 = date.sub(from: ts2, d: -24h)\r\n\r\nfrom(bucket: \"hichi\")\r\n  |> range(start: ts2, stop: te2)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"currentConsumption(16_7_0)\")\r\n  |> aggregateWindow(every: 1h, fn: mean)"
    }
   ]
  },
  {
   "title": "Average consumption for the last 24 hours",
   "type": "barchart",
   "description": "consumption per hour for the past 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"hichi\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"currentConsumption(16_7_0)\")\r\n  |> aggregateWindow(every: 1h, fn: mean)"
    }
   ]
  },
  {
   "title": "Average Hourly Consumption - past 12 months",
   "type": "barchart",
   "description": "mid consumption per hour for a day based on the past 12 months",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"hichi\")\r\n  |> range(start: -1y)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensor\"  and\r\n    r._field == \"currentConsumption(16_7_0)\"\r\n  )\r\n  |> map(fn: (r) => ({ r with hour: date.hour(t: r._time) }))\r\n  |> group(columns: [\"hour\"], mode:\"by\")\r\n  |> mean(column: \"_value\") \r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Weekly consumption",
   "type": "barchart",
   "description": "consumption per week for the past 12 months",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"hichi\")\r\n  |> range(start: - 12mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"currentConsumption(16_7_0)\")\r\n  |> aggregateWindow(every: 1h, fn: mean)\r\n  |> aggregateWindow(every: 1w, offset: -3d, fn: sum)\r\n  |> yield(name: \"some-name\")"
    }
   ]
  },
  {
   "title": "Monthly consumption",
   "type": "barchart",
   "description": "consumption per month for the past 12 months",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"hichi\")\r\n  |> range(start: -12mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"currentConsumption(16_7_0)\")\r\n  |> aggregateWindow(every: 1h, fn: mean)\r\n  |> aggregateWindow(every: 1mo, fn: sum)"
    }
   ]
  }
 ]
}