{
 "title": "solar panel",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Production",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensor\" and\r\n    r._field == \"Total Production\" and\r\n    r.sensor_id == \"id\"\r\n  )\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Energy Sold",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: -1w)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\" and r[\"_field\"] == \"Total Production\" and r[\"device_name\"] == \"tele (Other consumption monitor)\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\", \"device_name\"])\r\n  |> rename(columns: {_value: \"device1_value\", _time: \"device1_time\"})"
    }
   ]
  },
  {
   "title": "Generated power for the past 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"mqtt\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensor\" and\r\n    r._field == \"Current power\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "Weekly power generated ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"mqtt\")\r\n  |> range(start: - 12mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Current power\")\r\n  |> aggregateWindow(every: 1h, fn: mean)\r\n  |> aggregateWindow(every: 1w, offset: -3d, fn: sum, timeSrc:\"_start\")"
    }
   ]
  },
  {
   "title": "Daily power generation for the past 7 days",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nts = date.sub(from: today(), d: 1w)\r\nte = today()\r\nfrom(bucket: \"mqtt\")\r\n  |> range(start: ts, stop: te)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Current power\")\r\n  |> aggregateWindow(every: 1h, fn: mean)\r\n  |> aggregateWindow(every: 1d, fn: sum, timeSrc:\"_start\")"
    }
   ]
  },
  {
   "title": "Monthly power generated",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"mqtt\")\r\n  |> range(start: -12mo)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Current power\")\r\n  |> aggregateWindow(every: 1h, fn: mean)\r\n  |> aggregateWindow(every: 1mo, fn: sum, timeSrc:\"_start\")"
    }
   ]
  }
 ]
}